# Site settings
baseurl = "https://example.org/"
themesDir = "."
languageCode = "en-us"
title = "Alexander Phillips | Blog"
theme = "."
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[params]
	name = "Alexander Phillips"
	description = "Nonsensical ramblings and unintelligible posts."
	bio = "\"Please, for the love of God, stop sending me your blog posts.\" - Mom"
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Author of some nonsensical ramblings and unintelligible posts."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	#iconFont = "mono-social"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    #twitter  = "https://www.twitter.com/"
    #facebook = "https://www.facebook.com/"
    #github   = "https://www.github.com/"
    #dribble  = "https://www.dribbble.com/"
    linkedin = "https://www.linkedin.com/in/alexander-phillips-40431280/"
    github = "https://github.com/tatsuonline"
    link = "http://alexphillips.xyz"
    key = "http://alexphillips.xyz/documents/gpg-key.txt"